version: 2
jobs:
  build:
    docker:
      - image: ubcrocket/majortim-build
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            cd apdet-hanna
            ./build.sh
            cd ../sharedtest
            ./build.sh

      - store_artifacts:
          path: /builds/
