version: 2
jobs:
  build:
    docker:
      - image: ubcrocket/majortim-build
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            cd apdet_hanna
	    ls -l
            make -f Makefile_with_path
