version: 2
jobs:
  build:
    docker:
      - image: ubcrocket/majortimbuild
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            cd apdet_hanna
            ../dmake.sh
